### ISSUE TITLE
[cache] Expose only public API

### ISSUE THREAD

**Issue by hjdivad** [data-eden/data-eden#70]
**Tasks**:
- [ ] create `api.d.ts` and move public API there
- [ ] re-export API in `index.ts`
- [ ] confirm [docs](https://data-eden.github.io/data-eden/api/cache) work well w/this structure

Right now public interfaces and implementation are all co-mingled in `packages/cache/src/cache.ts`.  This causes two main issues:
1. It is very unclear to users what types & APIs are part of the public API (e.g. the types for options)
2. It is difficult for users to refer to public API types (e.g. the types for options)

A better organization would be:
  1. All public interfaces in `packages/cache/src/api.d.ts`
  2. `packages/cache/src/index.ts` re-exports the types in `api.d.ts`
  3. The implementation (in `cache.ts` and other files) imports the public API types

**Comment by shuba3862** [comment]
PR up for review https://github.com/data-eden/data-eden/pull/90
