### ISSUE TITLE
[cache] add types tests

### ISSUE THREAD

**Issue by hjdivad** [data-eden/data-eden#71]
**Tasks**:
- [ ] add `__tests__/types.d.ts`
  - [ ] use [ts-expect](https://github.com/TypeStrong/ts-expect) to validate public API

Example types tests that we need

Strongly, heterogenously typed cache values based on user key registries.  See [this example](https://tsplay.dev/NrnDlN).  As in the example, the value types (e.g. when you call `get`)  are inferred and the user does not have to supply the generics explicitly.

As in the example we want to cover:
  - [ ] `cache.get('invalid-key')` types to `never`
  - [ ] `cache.get('key-in-registry')` types correctly
  - [ ] `cache.get(keyPattern)` with `keyPattern` something like `urn:some-type:123` typing correctly.
