### ISSUE TITLE
[cache] transaction async APIs

### ISSUE THREAD

**Issue by hjdivad** [data-eden/data-eden#72]
**Tasks**
- [ ] make `transaction.get` async
- [ ] make `transaction.set` async
- [ ] `transaction.delete` does not need to use `Promise` directly as it's `async`
