### ISSUE TITLE
[cache] restructure tx.commit with cache locking

### ISSUE THREAD

**Issue by hjdivad** [data-eden/data-eden#81]
The current [tx.commit implementation](https://github.com/data-eden/data-eden/blob/78ac38b9c1f695d369d24699078e9ce2a46ababb/packages/cache/src/cache.ts#L872-L874) races a write promise with a timeout (called `commitLock`), but does not acquire a lock on the cache itself.

If two transactions commit at the same time it is possible to have undefined behaviour that will depend on the order in which the schedueler chooses to interleave the two async `tx.commit` invocations. This can result in lost data.

`commit` should acquire a cache lock (i.e. a cache-global lock) before doing any work.

Additionally, `tx.commit` should not write to the cache itself until it has called all userland hooks. This is to ensure that userland code can only corrupt the transaction (which can be thrown away) and not the entire cache.

So the transaction's work should be split into two phaes: `prepare` and `flush`.  During the preparation phase, entries are merged, userland hooks are called (`mergeStrategy`, `revisionStrategy`) &c. During `flush` nothing happens except writing to the cache itself (via `cache.#commitTransaction`).

This means that errors in userland code remain recoverable.

**tasks**
- [ ] add a `#lock: Transaction | null` on the cache
- [ ] add a `#acquireLock(this)` method on the cache (passed as friendly api to the constructor of the transaction)
- [ ] `tx.commit` awaits `acquireLock()` before doing any work
- [ ] `tx.commit` is split into prepare + flush
- [ ] userland errors (e.g. in `mergeStrategy`) don't corrupt the cache -- only the transaction
- [ ] similarly, only `prepare` can timeout -- once flush begins errors are unrecoverable
- [ ] `flush` mainly defers to the cache via `cache.#commitTransaction` which should be synchronous
- [ ] `tx.commit` releases its lock when it completes, whether successfully or not (i.e. in a `finally` block)
- [x] remove copying into `#cacheSnapshotBeforeCommit`
- [x] remove `rollback()`
